### ISSUE TITLE
Setup/Execution Issue

### ISSUE THREAD

**Issue by EminenceInCyber** [aapooksman/certmitm#13]
After connecting my phone to the certmitm setup which I am running in my Mac, I keep getting this error:

```
ERROR - [Errno 42] Protocol not available
Traceback (most recent call last):
  File "/Users/rkumar15/Documents/Tools/certmitm/certmitm.py", line 51, in threaded_connection_handler
    connection = certmitm.connection.connection(mitm_connection.downstream_socket, logger)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rkumar15/Documents/Tools/certmitm/certmitm/connection.py", line 28, in __init__
    self.upstream_ip, self.upstream_port = certmitm.util.sock_to_dest(self.client_socket)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rkumar15/Documents/Tools/certmitm/certmitm/util.py", line 244, in sock_to_dest
    dst = (sock.getsockopt(socket.SOL_IP, 80, 16))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 42] Protocol not available
```

Is there any way to solve this? What is causing the issue?

**Comment by asage-me** [comment]
I'm seeing the same issue with Kali Linux.  Were you able to figure this out?

**Comment by asage-me** [comment]
It has something to do with using NAT.  I'm using OPNsense and was NATing the traffic.  I switched over to a policy based rule with a gateway and it now works (mostly).  After a while I see the console output just doesn't update any more.  I haven't done any packet captures to verify if traffic is still coming in or not, but the client doesn't seem to notice so it has to be at least passing the traffic through.  I might dig into that more next weekend.
